spring:
  security:
    user:
      name: test   # ???
      password: 123456  # ??
      roles:   # ??
       - user
       - admin
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
      static-path-pattern: /static/**
